# SPDX-FileCopyrightText: 2022-2023 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: check

on:
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v24
      - name: Check .nix formatting
        run: nix fmt -- --fail-on-change
      - name: Check reuse lint
        run: nix develop --command reuse lint
      - name: Check nix flake show runs successfully
        run: nix flake show
      - name: Check that template is in tact
        run: |
          export GHAF_PATH=$(pwd)
          export TMP_DIR=${{ runner.temp }}/$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13)-ghaf-template-test

          mkdir -p $TMP_DIR && cd $TMP_DIR

          # # FIXME: Flake initialization command stuck, so we just copy template
          # nix flake init -t $GHAF_PATH#target-x86_64-generic
          cp -r $GHAF_PATH/templates/targets/x86_64/generic/* .
          sed "s|github:tiiuae/ghaf|path:${GHAF_PATH}|g" -i flake.nix

          nix flake show .
